### PR TITLE
fix Literal import for 3.6 and 3.7

### PR DESCRIPTION
**Pull request by agramfort**
cc @tomMoral @glemaitre @frcaud

### CODE REVIEW

**Review by marktennyson — APPROVED** [review]

**Comment by agramfort** [comment]
Thx. Could you make a bug fix release ?

**Comment by marktennyson** [comment]
I will release a new version shortly.
Thanks for making pull requests.

**Comment by marktennyson** [comment]
@agramfort 
Version 0.1.0 is released now.

**Comment by agramfort** [comment]
🙏

**Comment by marktennyson** [comment]
@agramfort 
Do you `mind` if I ask you to put a star on this `repository` ?
Anyway, thanks a lot for checking this python library.

**Comment by agramfort** [comment]
done !

but now I struggle with testing my views  with this using pytest asyncio... 🤦 

if you have any project I could look at for inspiration that would be great.

**Pull request merged**
